package invoicepdf

import (
	"fmt"
	"strings"

	"gopkg.aoctech.app/billing/api/internal/domain/billing"
	"gopkg.aoctech.app/billing/api/internal/domain/brcal"
)

// Lang is the language an invoice document is rendered in.
type Lang string

const (
	// PTBR is the default, and the language every document stored before
	// languages existed was rendered in.
	PTBR Lang = "pt-BR"
	EN   Lang = "en"
)

// Supported lists the languages a caller may ask for.
var Supported = []Lang{PTBR, EN}

// ParseLang maps a requested language to a supported one. Anything unknown or
// empty falls back to PTBR: a document in the wrong language is better than a
// refusal to give the customer their invoice.
func ParseLang(s string) Lang {
	s = strings.ToLower(strings.TrimSpace(s))
	switch {
	case s == "en" || strings.HasPrefix(s, "en-") || strings.HasPrefix(s, "en_"):
		return EN
	default:
		return PTBR
	}
}

// messages is one language's catalog: every label the document prints, plus
// the date and number conventions. Adding a language is adding an entry.
type messages struct {
	Title        string // "%s" is the invoice number
	PeriodLine   string // "%s" period, "%s" due date
	IssuedBy     string
	BilledTo     string
	Description  string
	Period       string
	Quantity     string
	UnitAmount   string
	Amount       string
	Prorated     string
	Subtotal     string
	Discount     string
	Total        string
	Footer       string
	PeriodRange  string // "%s" start, "%s" end
	dateLayout   func(d brcal.Date) string
	thousandsSep string
	decimalSep   string
	filename     string // "%d" is the invoice number
}

var catalogs = map[Lang]messages{
	PTBR: {
		Title:       "Fatura nº %s",
		PeriodLine:  "Período de %s · Vencimento em %s",
		IssuedBy:    "Emitida por",
		BilledTo:    "Cobrada de",
		Description: "Descrição",
		Period:      "Período",
		Quantity:    "Qtd.",
		UnitAmount:  "Unitário",
		Amount:      "Valor",
		Prorated:    "Proporcional aos dias usados",
		Subtotal:    "Subtotal",
		Discount:    "Desconto",
		Total:       "Total",
		Footer:      "Documento gerado por CTech Billing. É o demonstrativo da cobrança, não é nota fiscal.",
		PeriodRange: "%s a %s",
		dateLayout: func(d brcal.Date) string {
			return fmt.Sprintf("%d de %s de %d", d.Day, monthsPT[int(d.Month)-1], d.Year)
		},
		thousandsSep: ".",
		decimalSep:   ",",
		filename:     "fatura-%d.pdf",
	},
	EN: {
		Title:       "Invoice no. %s",
		PeriodLine:  "Period %s · Due on %s",
		IssuedBy:    "Issued by",
		BilledTo:    "Billed to",
		Description: "Description",
		Period:      "Period",
		Quantity:    "Qty.",
		UnitAmount:  "Unit price",
		Amount:      "Amount",
		Prorated:    "Prorated for the days used",
		Subtotal:    "Subtotal",
		Discount:    "Discount",
		Total:       "Total",
		Footer:      "Document generated by CTech Billing. It is the billing statement, not a tax invoice.",
		PeriodRange: "%s to %s",
		dateLayout: func(d brcal.Date) string {
			return fmt.Sprintf("%s %d, %d", monthsEN[int(d.Month)-1], d.Day, d.Year)
		},
		thousandsSep: ",",
		decimalSep:   ".",
		filename:     "invoice-%d.pdf",
	},
}

var monthsPT = [...]string{
	"janeiro", "fevereiro", "março", "abril", "maio", "junho",
	"julho", "agosto", "setembro", "outubro", "novembro", "dezembro",
}

var monthsEN = [...]string{
	"January", "February", "March", "April", "May", "June",
	"July", "August", "September", "October", "November", "December",
}

func (l Lang) msgs() messages {
	if m, ok := catalogs[l]; ok {
		return m
	}
	return catalogs[PTBR]
}

// Filename is the name the browser saves the document under.
func Filename(l Lang, number int64) string {
	return fmt.Sprintf(l.msgs().filename, number)
}

func (m messages) date(d brcal.Date) string {
	if d.IsZero() {
		return ""
	}
	return m.dateLayout(d)
}

func (m messages) period(start, end brcal.Date) string {
	if start.IsZero() || end.IsZero() {
		return ""
	}
	if m.decimalSep == "," {
		return fmt.Sprintf(m.PeriodRange,
			fmt.Sprintf("%02d/%02d/%04d", start.Day, int(start.Month), start.Year),
			fmt.Sprintf("%02d/%02d/%04d", end.Day, int(end.Month), end.Year))
	}
	return fmt.Sprintf(m.PeriodRange, m.date(start), m.date(end))
}

// money formats an amount with the language's separators. The currency symbol
// stays "R$": the amounts are reais in either language.
func (m messages) money(c billing.Cents) string {
	v := int64(c)
	sign := ""
	if v < 0 {
		sign, v = "-", -v
	}
	digits := fmt.Sprintf("%d", v/100)
	var b strings.Builder
	for i, r := range digits {
		if i > 0 && (len(digits)-i)%3 == 0 {
			b.WriteString(m.thousandsSep)
		}
		b.WriteRune(r)
	}
	return fmt.Sprintf("%sR$ %s%s%02d", sign, b.String(), m.decimalSep, v%100)
}
